const sampleAgencyData = [
  {
    id: 1,
    agencyName: "Agency 1",
    brandCount: 4,
    totalProjects: 18,
    completedProjects: 6,
    liveProject: 6,
    draftProjects: 6,
    totalSpends: "30,000",
  },
  {
    id: 2,
    agencyName: "Agency 2",
    brandCount: 5,
    totalProjects: 20,
    completedProjects: 5,
    liveProject: 7,
    draftProjects: 8,
    totalSpends: "20,000",
  },
  {
    id: 3,
    agencyName: "Agency 3",
    brandCount: 8,
    totalProjects: 11,
    completedProjects: 2,
    liveProject: 7,
    draftProjects: 2,
    totalSpends: "30,000",
  },
  {
    id: 4,
    agencyName: "Agency 4",
    brandCount: 3,
    totalProjects: 18,
    completedProjects: 6,
    liveProject: 6,
    draftProjects: 6,
    totalSpends: "45,000",
  },
  {
    id: 5,
    agencyName: "Agency 5",
    brandCount: 4,
    totalProjects: 45,
    completedProjects: 23,
    liveProject: 15,
    draftProjects: 7,
    totalSpends: "10,000",
  },
  {
    id: 6,
    agencyName: "Agency 6",
    brandCount: 19,
    totalProjects: 23,
    completedProjects: 6,
    liveProject: 9,
    draftProjects: 8,
    totalSpends: "15,000",
  },
  {
    id: 7,
    agencyName: "Agency 7",
    brandCount: 4,
    totalProjects: 18,
    completedProjects: 6,
    liveProject: 6,
    draftProjects: 6,
    totalSpends: "34,000",
  },
];

export default sampleAgencyData;
